version: '3.8'

services:
  app:
    build: .
    container_name: escola-api-app
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/escola
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      SPRING_PROFILES_ACTIVE: docker

  db:
    image: postgres:15
    container_name: escola-api-db
    ports:
      - "5432:5432"  # Porta do PostgreSQL
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: escola
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
